### PR TITLE
WAS-972 removing company-name format validation for 'Other' organisation-type

### PR DESCRIPTION
**Pull request by rickclare**

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Someone else needs to pick this up in my absence @rickclare

**Comment by rickclare** [comment]
@autotelik Can you PR this in conjunction with the related upstream PRs

https://github.com/EnvironmentAgency/waste-exemptions/pull/201
https://github.com/EnvironmentAgency/waste-exemptions-back-office/pull/91

**Comment by autotelik** [comment]
@rick ... looks good .. although seems to cover  more changes than the JIRA ticket specifies, JS changes and company number changes  - are they just due to rebase/merge ?

**Comment by autotelik** [comment]
@rickclare  ... looks good .. although seems to cover  more changes than the JIRA ticket specifies, JS changes and company number changes  - are they just due to rebase/merge ?

**Pull request merged**
