### PR TITLE
Feature/bulk upload

### PR DESCRIPTION
**Pull request by autotelik**
fixes to multi threading option - slower on local webrick server but worth testing a small run against passenger

task reports time elapsed so to see if threadign helps :

wes:bulk_load:import -n 100 -f page_applicant_contact 

wes:bulk_load:import -n 100 -f page_applicant_contact -m 3

### CODE REVIEW

**Comment by Cruikshanks** [comment]
@autotelik Have you just carried on using your old branch for fixing the multithreading stuff for this? I ask because the first 4 commits are now already in wex shared thanks to #89. Any chance you can create a new branch off of develop and cherry pick your last commit into it? Just worried this is going to get messy quickly.

**Comment by autotelik** [comment]
@Cruikshanks yeah I can do no problem .. but I did rebase this so the automatic merge option is on and so only the 1 file changed, is now part of this merge so won't that be ok  ?

**Comment by Cruikshanks** [comment]
Yeah, actually if you have rebased on develop that should be fine. When you're ready remember to force push and I can double check what the commits look like then.

**Comment by Cruikshanks** [comment]
@autotelik I've sorted out the commit history and also taken the liberty of resolving some rubocop warnings I saw in `bulk_load.thor`.

I've also updated it to allow me to test the command using the dummy app within the gem, which meant adding logic to check for the db type and altering the sql commands accordingly.

I'd be grateful if you could check you are happy with my changes (please feel free to improve what I've done if you can) and then I'll finish this PR off and get it merged.

**Comment by autotelik** [comment]
@Cruikshanks Looks good to me, also ran against spec/dummy and worked great

**Pull request merged**
